<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice CRUD MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=show_user">Show</a>
					</li>
					<li>
						<a href="index.php?route=create_user">Create</a>
					</li>
					<li>
						<a href="index.php?route=update_user">Update</a>
					</li>
					<li>
						<a href="index.php?route=list_user">list</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
		
		    if($route === "show_user"){
		        require "templates/Users/show.phtml";
		        
		    }else if($route === "create_user"){
		        require "templates/Users/create.phtml";
		        
		    }else if($route === "update_user"){
		        require "templates/Users/update.phtml";
		        
		    }else if ($route === "list_user"){
		    	require "templates/Users/list.phtml";
		    }
		    
		   
		?>
	</body>
</html>