<main>
	<h1>Page à create user</h1>
	<form method="post" action="">
      <input type="text" name="id" placeholder="id" required>
      <input type="email" name="email" placeholder="email" required>
      <input type="text" name="first_name" placeholder="first_name" required>
      <input type="text" name="last_name" placeholder="last_name" required>
      <button type="submit">Envoyer</button>
    </form>
</main>